"""empty message

Revision ID: 3202f1b7f16a
Revises: 
Create Date: 2018-09-03 15:19:55.560390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3202f1b7f16a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('os', sa.Enum('Undefined', 'MacOS', 'Windows', 'Linux', 'iOS', 'Android', 'WindowsPhone', name='oschoices'), nullable=False),
    sa.Column('device', sa.Enum('Undefined', 'Desktop', 'Tablet', 'Smartphone', 'SmartTV', 'Watch', name='devicechoices'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('user')
    # ### end Alembic commands ###
